comment:
  layout: "condensed_header, diff, flags, condensed_files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

flags:
  backend-unit:
    paths:
      - backend/src/
  backend-e2e:
    paths:
      - backend/src/
  frontend:
    paths:
      - frontend/src/
